apiVersion: actions.summerwind.dev/v1alpha1
kind: Runner
metadata:
  name: github-runner
  namespace: default
spec:
  repository: "denis-mikitich/test_repository"
  env:
    - name: DOCKER_OPTS
      value: "--insecure-registry=192.168.31.86:5050"
  volumeMounts: []
