stages:
  - build
  - deploy

variables:
  REGISTRY: 192.168.31.86:5050
  REGISTRY_URL: http://192.168.31.86:5050
  HELM_CHART: ./helm-chart
  NAMESPACE: default
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

before_script:
  - apk add --no-cache curl git docker
#  - mkdir -p /etc/docker
#  - echo '{"insecure-registries":["192.168.31.86:5050"]}' > /etc/docker/daemon.json
#  - dockerd --config-file /etc/docker/daemon.json &
#  - sleep 5
#  - docker login $REGISTRY -u root -p $CI_REGISTRY_PASSWORD
  - curl -LO "https://dl.k8s.io/release/v1.27.0/bin/linux/amd64/kubectl"
  - chmod +x kubectl && mv kubectl /usr/local/bin/
  - curl -LO "https://get.helm.sh/helm-v3.12.0-linux-amd64.tar.gz"
  - tar -xzf helm-v3.12.0-linux-amd64.tar.gz
  - mv linux-amd64/helm /usr/local/bin/helm

build-backend:
  stage: build
  tags:
    - k8s
  image: docker:latest
  services:
    - name: docker:20.10.16-dind
      command: ["--insecure-registry=192.168.31.86:5050"]
#  variables:
#    DOCKER_HOST: tcp://docker:2375
#    DOCKER_DRIVER: overlay2
  script:
    - docker login $REGISTRY_URL -u root -p $CI_REGISTRY_PASSWORD
    - docker build -t $REGISTRY/$CI_PROJECT_PATH:backend-$CI_COMMIT_SHA -f backend/Dockerfile ./backend
    - docker tag $REGISTRY/$CI_PROJECT_PATH:backend-$CI_COMMIT_SHA $REGISTRY/$CI_PROJECT_PATH:backend-latest
    - docker push $REGISTRY/$CI_PROJECT_PATH:backend-$CI_COMMIT_SHA
    - docker push $REGISTRY/$CI_PROJECT_PATH:backend-latest
  rules:
    - changes:
        - backend/**/*
        - Dockerfile

build-frontend:
  stage: build
  tags:
    - k8s
  image: docker:latest
  services:
    - name: docker:20.10.16-dind
      command: ["--insecure-registry=192.168.31.86:5050"]
#  variables:
#    DOCKER_HOST: tcp://docker:2375
#    DOCKER_DRIVER: overlay2
  script:
    - docker login $REGISTRY_URL -u root -p $CI_REGISTRY_PASSWORD
    - docker build -t $REGISTRY/$CI_PROJECT_PATH:frontend-$CI_COMMIT_SHA -f frontend/Dockerfile ./frontend
    - docker tag $REGISTRY/$CI_PROJECT_PATH:frontend-$CI_COMMIT_SHA $REGISTRY/$CI_PROJECT_PATH:frontend-latest
    - docker push $REGISTRY/$CI_PROJECT_PATH:frontend-$CI_COMMIT_SHA
    - docker push $REGISTRY/$CI_PROJECT_PATH:frontend-latest
  rules:
    - changes:
        - frontend/**/*
        - Dockerfile

deploy:
  stage: deploy
  tags:
    - k8s
  image: alpine/helm:3.12.0
  script:
    - helm upgrade --install my-app $HELM_CHART
        --set backend.image.repository=$REGISTRY/$CI_PROJECT_PATH
        --set backend.image.tag=backend-$CI_COMMIT_SHA
        --set frontend.image.repository=$REGISTRY/$CI_PROJECT_PATH
        --set frontend.image.tag=frontend-$CI_COMMIT_SHA
        --namespace $NAMESPACE
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  environment:
    name: production
