replicaCount: 1
imagePullSecrets:
  - name: gitlab-registry
backend:
  image:
    repository: 192.168.31.86:5050/root/my-app
    tag: backend-latest
    pullPolicy: Always
  service:
    port: 8081
    targetPort: 8081
  postgresql:
    host: postgresql
    port: 5432
    database: ci-db
    user: postgres
  redis:
    host: redis-master
    port: 6379
  fluentd:
    enabled: false
    host: localhost
    port: 24224
  debug: true

frontend:
  image:
    repository: 192.168.31.86:5050/root/my-app
    tag: frontend-latest
    pullPolicy: Always
  service:
    port: 80
    targetPort: 80
  ingress:
    host: app.local
    backendHost: my-app-backend-svc
    backendPort: 8081
