replicaCount: 1
imagePullSecrets:
#  - name: gitlab-registry
  - name: ghcr-secret
backend:
  image:
#    repository: 192.168.31.86:5050/root/my-app
    repository: ghcr.io/denis-mikitich/my-app-backend
#    tag: backend-latest
    tag: latest
    pullPolicy: IfNotPresent
  service:
    port: 8081
    targetPort: 8081
  postgresql:
    host: postgresql
    port: 5432
    database: ci-db
    user: postgres
  redis:
    host: redis-master
    port: 6379
  fluentd:
    enabled: false
    host: localhost
    port: 24224
  debug: true

frontend:
  image:
#    repository: 192.168.31.86:5050/root/my-app
    repository: ghcr.io/denis-mikitich/my-app-frontend
#    tag: frontend-latest
    tag: latest
    pullPolicy: IfNotPresent
  service:
    port: 80
    targetPort: 80
  ingress:
    host: app.local
    backendHost: my-app-backend-svc
    backendPort: 8081
