fullnameOverride: nexus
replicas: 1
persistence:
  enabled: true
  size: 10Gi
service:
  type: ClusterIP
  port: 8081
ingress:
  enabled: false
chownDataDir: false
resources:
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi