fullnameOverride: nexus
replicas: 1
persistence:
  enabled: true
  size: 10Gi
  storageClass: local-path
service:
  type: ClusterIP
  port: 8081
  additionalPorts:
    - port: 8083
      name: docker-hosted
      containerPort: 8083
ingress:
  enabled: false
chownDataDir: true
resources:
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    cpu: 1
    memory: 2Gi
bashImage:
  repository: docker.io/library/bash
  tag: "5.2"
  pullPolicy: IfNotPresent
