apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: java-app
  namespace: argocd
spec:
  commonUpdateSettings:
    updateStrategy: semver

  writeBackConfig:
    method: git:secret:github-repo-credentials
    gitConfig:
      branch: test-task
      writeBackTarget: helmvalues:/apps/java-app/values.yaml

  applicationRefs:
    - namePattern: java-app

      images:
        - alias: frontend
          imageName: 192.168.100.14:30083/test/ci-frontend:~1.0.0
