architecture: standalone

auth:
  enabled: false
#  existingSecret: redis-auth
#  existingSecretPasswordKey: redis-password

master:
  persistence:
    enabled: true
    size: 1Gi
    storageClass: local-path

  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi