apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc
  namespace: argocd
spec:
  project: default

  sources:
    - repoURL: ghcr.io/actions/actions-runner-controller-charts
      chart: gha-runner-scale-set-controller
      targetRevision: 0.13.1
      helm:
        valueFiles:
          - $values/infrastructure/arc/values.yaml
    
    - repoURL: https://github.com/denis-mikitich/test_repository.git
      targetRevision: test-task
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: arc-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true