apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: java-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/denis-mikitich/test_repository.git
    targetRevision: test-task
    path: apps/java-app

  destination:
    server: https://kubernetes.default.svc
    namespace: java-app

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true