apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
spec:
  project: default

  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      chart: redis
      targetRevision: 24.0.1
      helm:
        valueFiles:
          - $values/infrastructure/redis/values.yaml

    - repoURL: https://github.com/denis-mikitich/test_repository.git
      targetRevision: test-task
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: redis

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true