architecture: standalone

auth:
  username: postgres
  database: ci-db
  existingSecret: postgresql-credentials
  secretKeys:
    adminPasswordKey: postgres-password
    userPasswordKey: password

primary:
  persistence:
    enabled: true
    size: 5Gi
    storageClass: local-path

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi